<a href="https://colab.research.google.com/github/srustihs/ML_2023/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy or nd
Numpy is a python library for creating and manipulating matrics, the main data structure used by ML algorithms.Metrics are mathematical objects used to store values in rows and columns.
NumPy is a powerful  library in python that provides support for array and matrics

In [ ]:
import numpy as np

In [ ]:
#create numpy or nd array
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.array(24)
print(arr1)
print(arr1.ndim) #for finding dimension of an array

24
0


In [ ]:
arr1=np.array(24)
print(arr1)
print('dimension: ',arr1.ndim)
print('shape: ',arr1.shape)

24
dimension:  0
shape:  ()


In [ ]:
#1-D array: To create a one-dimensional array specify a layer of square brackets
arr1=np.array([2,3,4])
print(arr1)
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

[2 3 4]
dimension: 1
shape: (3,)


bcz no layer at all

In [ ]:
#2-D array
arr1=np.array([[2,3,4],[4,5,6]])
print(arr1)
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

[[2 3 4]
 [4 5 6]]
dimension: 2
shape: (2, 3)


Shape=row(layer),column 

In [ ]:
#create a 2D array whose shape=(3,3)
arr1=np.array([[2,3,4],[4,5,6],[7,8,9]])
print(arr1)
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
dimension: 2
shape: (3, 3)


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

[1 2 3]
dimension: 1
shape: (3,)


In [ ]:
arr1=np.array([[2,3,4]])
print(arr1)
print(arr1.shape)
print(arr1.ndim)

[[2 3 4]]
(1, 3)
2


In [ ]:
#Create a 2D array whose shape is(4,3)
arr1=np.array([[1,2,3],[4,5,6],[7,8,9],[1,4,7]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 7]]
2
(4, 3)


3D=2D+2D

In [ ]:
#Create a 3D array whose shape is
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9],[1,4,7]],[[1,2,3],[4,5,6],[7,8,9],[1,4,7]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 4 7]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 4 7]]]
3
(2, 4, 3)


In [ ]:
#Create a 4D array
arr1=np.array([[[[1,2,3],[4,5,6],[7,8,9],[1,4,7]],[[1,2,3],[4,5,6],[7,8,9],[1,4,7]]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]
   [1 4 7]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]
   [1 4 7]]]]
4
(1, 2, 4, 3)


In [ ]:
arr1=np.array([[[[1,2,3],[4,5,6],[7,8,9],[1,4,7]]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]
   [1 4 7]]]]
4
(1, 1, 4, 3)


In [ ]:
arr1=np.array([[[[1,2,3],[4,5,6],[7,8,9],[1,4,7]]],[[[1,2,3],[4,5,6],[7,8,9],[1,4,7]]]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]
   [1 4 7]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]
   [1 4 7]]]]
4
(2, 1, 4, 3)


0D array has 0 square bracket
1D array has 1 square bracket
2D array has 2 square bracket
3D array has 3 square bracket

In [ ]:
arr1=np.array([1,2,3,4], ndmin=2)
print(arr1)
print(arr1.ndim)

[[1 2 3 4]]
2


In [ ]:
arr1=np.array([1,2,3,4], ndmin=5)
print(arr1)
print(arr1.ndim)

[[[[[1 2 3 4]]]]]
5


shape should be same
Dimension can be different

In [ ]:
#Create two 1D arrays
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
arr3=arr1+arr2
print(arr3)

[ 4  6  8 10]


In [ ]:
arr1=np.array([[1,2,3,4],[3,4,5,6]])
arr2=np.array([3,4,5,6])
arr3=arr1+arr2
print(arr3)

[[ 4  6  8 10]
 [ 6  8 10 12]]


In [ ]:
arr1=np.array([[1,2,3,4],[3,4,5,6]])
arr2=np.array([[3,4,5,6],[4,5,6,7]])
arr3=arr1+arr2
print(arr3)

[[ 4  6  8 10]
 [ 7  9 11 13]]


NUmpy array indexing

In [ ]:
arr1=np.array([1,2,3,4])
print(arr1[-4])

1


In [ ]:
arr1=np.array([1,2,3,4])
print(arr1[2])

3


In [ ]:
#Program to calculate sum of all the items in a 1D array
arr1=np.array([1,2,3,4])
sum=0
for i in arr1:
  sum+=i
print(sum)

110


In [ ]:
#Create a 2D array in which the !D arrays are [1,2,3] and [3,4,5]
arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[1][1])


4


In [ ]:
arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[1][0],arr1[1][1])

3 4


In [ ]:
arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[1,0:2])

[3 4]


In [ ]:
arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[0:2,0:2])


[[1 2]
 [3 4]]


In [ ]:
arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[0,0:2],arr1[1,0:2])

[1 2] [3 4]


Access elements of a 3D array arr1=np.array()

In [ ]:
#create a 3D array containing
#[[1,2,3],[3,4,5]]
#[[5,6,7],[7,8,9]]
arr1=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr1[0,0,0])

1


In [ ]:
#create a 3D array containing
#[[1,2,3],[3,4,5]]
#[[5,6,7],[7,8,9]]
arr1=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr1.ndim)
print(arr1)
print(arr1[0,0,0])

In [ ]:
#create a 3D array containing
#[[1,2,3],[3,4,5]]
#[[5,6,7],[7,8,9]]
import numpy as np
arr1=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr1.ndim)
print(arr1)
print(arr1[x,a,e])

3
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]


NameError: ignored

In [ ]:
#create a 3D array containing
#[[1,2,3],[3,4,5]]
#[[5,6,7],[7,8,9]]
arr1=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr1.ndim)
print(arr1)
print(arr1[0,1,1])

3
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
4


In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
  for d in x:
    print(d)
  

1
2
3
4
5
6


In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
  for y in x:
    print(x)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
  for y in x:
    print(y,end=' ')

1 2 3 4 5 6 

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
    print(x,end=' ')

[1 2 3] [4 5 6] 

In [ ]:
#print scalar values 0D array elements of 3D numpy  array
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
for x in arr1:
  for y in x:
    print(y,end=' ')

[1 2 3] [4 5 6] [7 8 9] [0 1 2] 

In [ ]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
for x in arr1:
  for y in x:
    for z in y:
     print(z,end=' ')
print()     
print('shape: ',arr1.shape)

1 2 3 4 5 6 7 8 9 0 1 2 
shape:  (2, 2, 3)


In [ ]:
#nditer()
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
for x in np.nditer(arr1):
  print(x,end=' ')


1 2 3 4 5 6 7 8 9 0 1 2 

Populate arrays with sequence numbers:
arange()

In [ ]:
arr1=np.arange(5,12)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[ 5  6  7  8  9 10 11]
1
(7,)


In [ ]:
arr1=np.arange(5,12,2)
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[ 5  7  9 11]
1
(4,)


Populate array with random numbers:
np.random.randint(low,high,size)

In [ ]:
arr1=np.random.randint(low=10,high=20,size=(6))
print(arr1)

[12 16 17 10 16 17]


In [ ]:
arr1=np.random.randint(low=5,high=30,size=(9))
print(arr1)

[14 12 21 27 17  9  7 18 20]


In [ ]:
arr1=np.random.randint(low=5,high=30,size=(6,2)) #row,column
print(arr1)

[[22 10]
 [20 18]
 [29  8]
 [26 10]
 [19 15]
 [ 7 23]]


In [ ]:
arr1=np.random.randint(low=5,high=30,size=(6,2,2)) #row,column
print(arr1)

[[[ 8 17]
  [ 5  8]]

 [[ 5 26]
  [15  6]]

 [[21 25]
  [18 29]]

 [[19  7]
  [17 12]]

 [[19 14]
  [16  5]]

 [[28 26]
  [16 11]]]


In [ ]:
arr1=np.random.randint(low=5,high=30,size=(6,2,2,2)) #row,column
print(arr1)

[[[[22 16]
   [21 26]]

  [[12 11]
   [21  7]]]


 [[[ 7 29]
   [20 14]]

  [[12 12]
   [13 13]]]


 [[[13 14]
   [13 19]]

  [[ 8  8]
   [ 9 20]]]


 [[[11 23]
   [13 24]]

  [[29 17]
   [21 16]]]


 [[[24 26]
   [ 5 17]]

  [[24  9]
   [27 15]]]


 [[[15 11]
   [ 6 11]]

  [[ 7 22]
   [20 29]]]]


In [ ]:
arr1=np.random.randint(low=5,high=30,size=(3,2,3,4,3)) #row,column
print(arr1)

[[[[[26 18 24]
    [28 15 19]
    [16  7 25]
    [11 21 23]]

   [[10 10 17]
    [29 23 26]
    [22 24 27]
    [18 11 28]]

   [[15 23 11]
    [14 21 22]
    [17 16 19]
    [24 26  5]]]


  [[[29 17 17]
    [22  9 28]
    [16 21 21]
    [ 6 19  6]]

   [[22  8  8]
    [29 27 29]
    [ 5 20 13]
    [19 22 13]]

   [[ 6 27  5]
    [26 10 13]
    [ 8 14  9]
    [25 29 27]]]]



 [[[[20 18  6]
    [ 5 18 23]
    [ 9 18 28]
    [14  7 22]]

   [[24 25  7]
    [16 21 19]
    [14 26 27]
    [20 16 23]]

   [[29  5 17]
    [ 8 23 16]
    [17 29 21]
    [19  8 27]]]


  [[[20 27 22]
    [ 8 16 27]
    [16 26 19]
    [19 18 21]]

   [[ 7 22 26]
    [11  7 10]
    [ 7  6 22]
    [27 28 11]]

   [[28 28 19]
    [25  5  5]
    [27  7 18]
    [24 13 13]]]]



 [[[[16  9 24]
    [16 17 27]
    [25 16 27]
    [18 11 25]]

   [[ 8 21 28]
    [29 16 16]
    [ 8 22 17]
    [ 9 19 10]]

   [[29 29 27]
    [17  8  9]
    [11 19 14]
    [ 5 29 12]]]


  [[[20 26 24]
    [22 14 20]
    [16 13 19]
    [10 10 

Broadcasting:
2=[[2,2,2],[2,2,2]]

In [ ]:
arr1=np.array([[2,3,4],[5,6,7]])
print(arr1 + 2)
print(arr1*2)

[[4 5 6]
 [7 8 9]]
[[ 4  6  8]
 [10 12 14]]


In [ ]:
arr1=np.array([[2,3,4],[5,6,6]])
print(arr1*5)

[[10 15 20]
 [25 30 30]]


Create a linear Dataset
Create a simple dataset consisting of a single feature and a label as follows:
1. Assign a sequence of integers from 6 to 20(inclusive) to a Numpy array named feature.
2. Assign 15 values to a NumPy array named label such that:

label=(3)(feature)+4
For example,the first value for label should be:
label=(3)(6)+4=22

In [ ]:
feature=np.arange(6,21)
label=3*feature+4
print(feature)
print(label)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
